2021-05-28 18:29:10,282 INFO    MainThread:21673 [wandb_setup.py:_flush():69] setting env: {}
2021-05-28 18:29:10,283 INFO    MainThread:21673 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-28 18:29:10,283 INFO    MainThread:21673 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-28 18:29:10,283 INFO    MainThread:21673 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-28 18:29:10,284 INFO    MainThread:21673 [wandb_init.py:_log_setup():336] Logging user logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210528_182910-2agc4gtu/logs/debug.log
2021-05-28 18:29:10,284 INFO    MainThread:21673 [wandb_init.py:_log_setup():337] Logging internal logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210528_182910-2agc4gtu/logs/debug-internal.log
2021-05-28 18:29:10,284 INFO    MainThread:21673 [wandb_init.py:init():369] calling init triggers
2021-05-28 18:29:10,285 INFO    MainThread:21673 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-28 18:29:10,285 INFO    MainThread:21673 [wandb_init.py:init():418] starting backend
2021-05-28 18:29:10,285 INFO    MainThread:21673 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-28 18:29:10,300 INFO    MainThread:21673 [backend.py:ensure_launched():132] starting backend process...
2021-05-28 18:29:10,306 INFO    MainThread:21673 [backend.py:ensure_launched():136] started backend process with pid: 21697
2021-05-28 18:29:10,307 INFO    MainThread:21673 [wandb_init.py:init():423] backend started and connected
2021-05-28 18:29:10,310 INFO    MainThread:21673 [wandb_init.py:init():465] updated telemetry
2021-05-28 18:29:10,310 INFO    MainThread:21673 [wandb_init.py:init():484] communicating current version
2021-05-28 18:29:11,372 INFO    MainThread:21673 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-28 18:29:11,372 INFO    MainThread:21673 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-28 18:29:11,787 INFO    MainThread:21673 [wandb_init.py:init():522] starting run threads in backend
2021-05-28 18:29:12,913 INFO    MainThread:21673 [wandb_run.py:_console_start():1565] atexit reg
2021-05-28 18:29:12,914 INFO    MainThread:21673 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-28 18:29:12,914 INFO    MainThread:21673 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-28 18:29:12,915 INFO    MainThread:21673 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-28 18:29:12,915 INFO    MainThread:21673 [wandb_init.py:init():546] run started, returning control to user process
2021-05-28 18:29:12,915 INFO    MainThread:21673 [wandb_config.py:__setitem__():141] config set epochs = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f58b4431640>>
2021-05-28 18:29:12,915 INFO    MainThread:21673 [wandb_run.py:_config_callback():787] config_cb epochs 10 None
2021-05-28 18:29:12,916 INFO    MainThread:21673 [wandb_config.py:__setitem__():141] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7f58b4431640>>
2021-05-28 18:29:12,916 INFO    MainThread:21673 [wandb_run.py:_config_callback():787] config_cb batch_size 32 None
2021-05-28 18:29:20,702 INFO    MainThread:21673 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-28 18:29:20,703 INFO    MainThread:21673 [wandb_run.py:_restore():1507] restore
2021-05-28 18:29:22,715 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 926
  total_bytes: 926
}

2021-05-28 18:29:23,035 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 926
  total_bytes: 926
}

2021-05-28 18:29:23,816 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 926
  total_bytes: 2558
}

2021-05-28 18:29:24,187 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,291 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,396 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,500 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,603 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,707 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:24,811 INFO    MainThread:21673 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2571
  total_bytes: 2571
}

2021-05-28 18:29:26,129 INFO    MainThread:21673 [wandb_run.py:_show_files():1879] logging synced files
