2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_setup.py:_flush():69] setting env: {}
2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'f97918185ed02886a90fa4464e7469c13c017460'}
2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_init.py:_log_setup():336] Logging user logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_130604-3t6nhdg0/logs/debug.log
2021-05-27 13:06:04,316 INFO    MainThread:37083 [wandb_init.py:_log_setup():337] Logging internal logs to /home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/AutoencoderModel/wandb/run-20210527_130604-3t6nhdg0/logs/debug-internal.log
2021-05-27 13:06:04,317 INFO    MainThread:37083 [wandb_init.py:init():369] calling init triggers
2021-05-27 13:06:04,317 INFO    MainThread:37083 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-27 13:06:04,317 INFO    MainThread:37083 [wandb_init.py:init():418] starting backend
2021-05-27 13:06:04,317 INFO    MainThread:37083 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-27 13:06:04,329 INFO    MainThread:37083 [backend.py:ensure_launched():132] starting backend process...
2021-05-27 13:06:04,335 INFO    MainThread:37083 [backend.py:ensure_launched():136] started backend process with pid: 37111
2021-05-27 13:06:04,336 INFO    MainThread:37083 [wandb_init.py:init():423] backend started and connected
2021-05-27 13:06:04,338 INFO    MainThread:37083 [wandb_init.py:init():465] updated telemetry
2021-05-27 13:06:04,339 INFO    MainThread:37083 [wandb_init.py:init():484] communicating current version
2021-05-27 13:06:04,787 WARNING MainThread:37083 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 744, in init
    run = wi.init()
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 485, in init
    ret = backend.interface.communicate_check_version(
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 789, in communicate_check_version
    result = self._communicate(rec)
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/veror/Desktop/Uni/Applied Machine Learning/Challenge/ML_project/venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
